#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  vimcompatible = true
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "muon"
  colorscheme_bg = "dark"

  # true colors
  enable_guicolors = true

  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "nil"
  statusline_iseparator = "nil"
  buffer_index_type = 0

  enable_tabline_filetype_icon = true

  # Enable/Disable show mode on statusline
  enable_statusline_mode = false

  # left sections of statusline
  statusline_left_sections = []

  # right sections of statusline
  statusline_right_sections = [
    'cursorpos',
    'percentage',
  ]

  # load vice
  bootstrap_before = 'adaptor#before'
  bootstrap_after = 'adaptor#after'

  # hide file
  enable_vimfiler_welcome = false
  filemanager = "nerdtree"

  # Disable various spacevim remaps
  enable_language_specific_leader = false
  escape_key_binding = ''
  windows_leader = ''
  windows_smartclose = ''

  # Update SpaceVim automatically
  automatic_update = true

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  enable = true
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  enable = true
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "colorscheme"
  enable = true

[[layers]]
  name = "core#statusline"
  enable = true

[[layers]]
  name = "ui"
  enable = true
  enable_sidebar = true
  enable_scrollbar = true
  enable_indentline = true
  enable_cursorword = true
  indentline_char = ' '
  conceallevel = 0
  concealcursor = ''
  cursorword_delay = 50
  cursorword_exclude_filetype = []
  indentline_exclude_filetype = []

[[layers]]
  name = "incsearch"
  enable = true
